version: '2.0'
volumes:
    dbdata_mariadb:
        driver: local
services:
    mariadb:
        env_file:
            - ./.env
        image: 'mariadb:10.4.0-bionic'
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
        volumes:
            - 'dbdata_mariadb:/var/lib/mysql'
        ports:
            - '$MYSQL_PORT:3306'
        stdin_open: true
        tty: true
