swagger: '2.0'
info:
  version: 1.0.0
  title: API Explorer Dev
contact:
  name: Heckatlon Koper
  email: mihafink333@gmail.com
consumes:
  - application/json
  - application/x-www-form-urlencoded
produces:
  - application/json
  - text/html
basePath: /api
paths:
  /auth/login:
    post:
      tags:
        - Auth
      description: Login.
      summary: auth.login&nbsp&nbsp&nbsp&nbsp-&nbsp&nbsp&nbsp&nbspLogin.
      operationId: auth.login
      x-controller:
        - file: auth
          handler: login
      parameters:
        - name: email
          in: formData
          description: ''
          required: true
          type: string
        - name: password
          in: formData
          description: ''
          required: true
          type: string
  /auth/logout:
    get:
      tags:
        - Auth
      description: Logout.
      summary: auth.logout&nbsp&nbsp&nbsp&nbsp-&nbsp&nbsp&nbsp&nbspLogout.
      operationId: auth.logout
      x-controller:
        - file: auth
          handler: logout
      parameters: []
  /location/all:
    get:
      tags:
        - Location
      description: Get List of locations.
      summary: >-
        location.index&nbsp&nbsp&nbsp&nbsp-&nbsp&nbsp&nbsp&nbspGet List of
        locations.
      operationId: location.index
      x-controller:
        - file: location
          handler: index
      parameters: []
  '/location/{id}':
    get:
      tags:
        - Location
      description: Get location by id.
      summary: >-
        location.location&nbsp&nbsp&nbsp&nbsp-&nbsp&nbsp&nbsp&nbspGet location
        by id.
      operationId: location.location
      x-controller:
        - file: location
          handler: getLocation
      parameters:
        - name: id
          in: path
          description: Location id.
          required: true
          type: integer
  '/route/{id}':
    get:
      tags:
        - Route
      description: Get route by id.
      summary: route.route&nbsp&nbsp&nbsp&nbsp-&nbsp&nbsp&nbsp&nbspGet route by id.
      operationId: route.route
      x-controller:
        - file: route
          handler: getRoute
      parameters:
        - name: id
          in: path
          description: Route id.
          required: true
          type: integer
  /users:
    post:
      tags:
        - User
      description: Register a new user.
      summary: users.store&nbsp&nbsp&nbsp&nbsp-&nbsp&nbsp&nbsp&nbspRegister a new user.
      operationId: users.store
      x-controller:
        - file: user
          handler: store
      parameters:
        - name: email
          in: formData
          description: ''
          required: true
          type: string
        - name: password
          in: formData
          description: >-
            Please enter stronger password. Use at least 1 lowercase character
            and at least 1 number.
          required: true
          type: string
        - name: role
          in: formData
          description: 'Available roles: ''admin'' or ''user''.'
          required: true
          type: string
  /users/email:
    get:
      tags:
        - User
      description: Check if a user with the given email already exists.
      summary: >-
        users.email.show&nbsp&nbsp&nbsp&nbsp-&nbsp&nbsp&nbsp&nbspCheck if a user
        with the given email already exists.
      operationId: users.email.show
      x-controller:
        - file: user
          handler: showEmail
      parameters:
        - name: email
          in: query
          description: ''
          required: true
          type: string
  /users/me:
    get:
      tags:
        - User
      description: Get the logged in user.
      summary: >-
        users.showMe&nbsp&nbsp&nbsp&nbsp-&nbsp&nbsp&nbsp&nbspGet the logged in
        user.
      operationId: users.showMe
      x-controller:
        - file: user
          handler: showMe
      parameters: []
    put:
      tags:
        - User
      description: Update the logged in user.
      summary: >-
        users.updateMe&nbsp&nbsp&nbsp&nbsp-&nbsp&nbsp&nbsp&nbspUpdate the logged
        in user.
      operationId: users.updateMe
      x-controller:
        - file: user
          handler: updateMe
      parameters:
        - name: first_name
          in: formData
          description: ''
          required: false
          type: string
        - name: last_name
          in: formData
          description: ''
          required: false
          type: string
        - name: backup_email
          in: formData
          description: ''
          required: false
          type: string
        - name: work_phone
          in: formData
          description: ''
          required: false
          type: string
        - name: private_phone
          in: formData
          description: ''
          required: false
          type: string
        - name: old_password
          in: formData
          description: If you want to change the password you must enter the old password.
          required: false
          type: string
        - name: password
          in: formData
          description: >-
            Password must contain at least 1 uppercase, 1 lowercase, 1 numeric
            and 1 special character.
          required: false
          type: string
        - name: is_sms_notify_enabled
          in: formData
          description: ''
          required: false
          type: boolean
        - name: notify_phone
          in: formData
          description: ''
          required: false
          type: string
        - name: is_email_notify_enabled
          in: formData
          description: ''
          required: false
          type: boolean
        - name: notify_email
          in: formData
          description: ''
          required: false
          type: string
        - name: is_push_notify_enabled
          in: formData
          description: ''
          required: false
          type: boolean
    delete:
      tags:
        - User
      description: Delete the logged in user.
      summary: >-
        users.destroyMe&nbsp&nbsp&nbsp&nbsp-&nbsp&nbsp&nbsp&nbspDelete the
        logged in user.
      operationId: users.destroyMe
      x-controller:
        - file: user
          handler: destroyMe
      parameters: []
  /verify/send/email:
    post:
      tags:
        - Verify
      description: Resend verification e-mail.
      summary: >-
        verify.sendEmail&nbsp&nbsp&nbsp&nbsp-&nbsp&nbsp&nbsp&nbspResend
        verification e-mail.
      operationId: verify.sendEmail
      x-controller:
        - file: verify
          handler: sendVerifyEmail
      parameters:
        - name: email
          in: formData
          description: User's email.
          required: true
          type: string
  /verify/verify/token:
    post:
      tags:
        - Verify
      description: Verify verification token.
      summary: >-
        verify.verifyToken&nbsp&nbsp&nbsp&nbsp-&nbsp&nbsp&nbsp&nbspVerify
        verification token.
      operationId: verify.verifyToken
      x-controller:
        - file: verify
          handler: verifyToken
      parameters:
        - name: token
          in: formData
          description: ''
          required: true
          type: string
  /verify/verify:
    post:
      tags:
        - Verify
      description: Verify user's email.
      summary: >-
        verify.verify&nbsp&nbsp&nbsp&nbsp-&nbsp&nbsp&nbsp&nbspVerify user's
        email.
      operationId: verify.verify
      x-controller:
        - file: verify
          handler: verify
      parameters:
        - name: token
          in: formData
          description: ''
          required: true
          type: string
description: API.
